[package]
name = "geolocate"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
maxminddb = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"
reqwest = { version = "0.11", features = ["blocking", "json"] }
